/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    BinaryControl: typeof import('./src/components/DeviceControls/BinaryControl.vue')['default']
    ConnectionNavbarActions: typeof import('./src/components/ConnectionNavbarActions.vue')['default']
    DeviceCard: typeof import('./src/components/DeviceCard.vue')['default']
    EnumControl: typeof import('./src/components/DeviceControls/EnumControl.vue')['default']
    FeatureHeader: typeof import('./src/components/DeviceControls/FeatureHeader.vue')['default']
    InstanceMenu: typeof import('./src/components/InstanceMenu.vue')['default']
    NumericControl: typeof import('./src/components/DeviceControls/NumericControl.vue')['default']
    PermitJoinToastDescription: typeof import('./src/components/PermitJoinToastDescription.vue')['default']
    PermitJoinToggle: typeof import('./src/components/PermitJoinToggle.vue')['default']
    ReadonlyFeature: typeof import('./src/components/DeviceControls/ReadonlyFeature.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./src/components/SettingsMenu.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UChip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDashboardToolbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    USlider: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.0_@tiptap+extensions@3.20.5_@tiptap+core@3.20.5_@tiptap+pm@3.20.5__@tiptap_5bfeaa25318c6aaf5cd62041128981a6/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
