name: Velora
version: "0.0.5"
slug: velora
description: Alternative Zigbee2MQTT web UI
url: https://github.com/codewec/velora
ingress: true
ingress_port: 8080
panel_icon: mdi:graph-outline
panel_title: Velora
init: false
startup: application
arch:
  - amd64
  - aarch64
options:
  z2m_targets_json: ""
schema:
  z2m_targets_json: str?
